### ISSUE TITLE
[6]  Сhange product name staff control to idle control

### ISSUE THREAD

**Issue by ghost** [5sControl/idle_control#7]
Нужно изменить название продукта

- [ ] - описание на странице, блог, данные внизу, описание продукта
https://github.com/5sControl/idle_control/issues/7#issuecomment-1357161890
https://github.com/5sControl/idle_control/issues/7#issuecomment-1357164635
https://github.com/5sControl/idle_control/issues/7#issuecomment-1357165417

**Comment by ghost** [comment]
Ожидаемый результат:
Idle Control
Фактический результат:

![Image](https://user-images.githubusercontent.com/120357489/208361702-aec96d03-8b4d-4cbb-848a-69e96ff3054a.PNG)

**Comment by ghost** [comment]
Ожидаемый результат: Idle Control
Фактический результат:

![Image](https://user-images.githubusercontent.com/120357489/208362505-3cb0b8a8-260c-4931-8ffb-9a2c23c42d9d.jpg)

**Comment by ghost** [comment]
Ожидаемый результат: Idle Control
Фактический результат:
![Image](https://user-images.githubusercontent.com/120357489/208362724-8b3090bc-7a5b-4f31-bf64-77b1899e47da.PNG)

**Comment by ghost** [comment]
Ожидаемый результат: при нажатии на иконку ютуба - переход на ссылку в ютуб
https://www.youtube.com/channel/UCs6pBUahhTcuLqhMhaeW3aA

Фактический результат: Возвращает на стартовую страницу 
![Image](https://user-images.githubusercontent.com/120357489/208364238-de247b6c-5e44-47cf-b2cf-e232ac49f34e.PNG)

**Comment by ZelGaDisA** [comment]
ready
